language: generic

sudo: required

services: 
  - docker

before_install: 
  - docker build -t roccodevhf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roccodevhf/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  enviroment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-222881772730"
  bucket_path: "docker-react"
  on:
    branch: "master"
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: 
      secure: "$SECRET_ACCESS_KEY"

