language: generic

sudo: required
services: 
  - docker

before_install: 
  - docker build -t roccodevhf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roccodevhf/docker-react npm run test
  
